'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property Id As Integer
    Public Property Name As String
    Public Property Title As String
    Public Property Manager As Nullable(Of Integer)
    Public Property HireDate As Nullable(Of Date)
    Public Property Salary As Nullable(Of Decimal)
    Public Property DepartmentId As Nullable(Of Integer)

    Public Overridable Property Department As Department

End Class
